### ISSUE TITLE
깃헙 레포 주소가 잘못됨.

### ISSUE THREAD

**Issue by Migan178** [NyangLab/MirTerminal#3]
# 무엇이 문제인가요?
- 현재 이 레포의 주소는 https://github.com/NyangLab/MirTerminal 임. 하지만 터미널에 뜨는 깃헙 레포 주소는 https://github.com/ImNyang/MirTerminal 으로 되어있음.

**Comment by Migan178** [comment]
- 때문에 404 Not Found에러 발생.

**Comment by ImNyang** [comment]
[Commit 43](https://github.com/NyangLab/MirTerminal/commit/8873be9bd933c743a25232032ebdc55234589824)에서 해결
